// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj1kUcnjtUzvlrKvXuXiMCxqQ3Fplw94Y',
    appId: '1:1065906049975:web:fcd9a525e407830ef44e32',
    messagingSenderId: '1065906049975',
    projectId: 'newtest-90b54',
    authDomain: 'newtest-90b54.firebaseapp.com',
    databaseURL: 'https://newtest-90b54-default-rtdb.firebaseio.com',
    storageBucket: 'newtest-90b54.appspot.com',
    measurementId: 'G-X01HYC5VLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAie09_cMh2lGAYJXUkbwXURtIhxVSpvgc',
    appId: '1:1065906049975:android:8e67a64a79f17bebf44e32',
    messagingSenderId: '1065906049975',
    projectId: 'newtest-90b54',
    databaseURL: 'https://newtest-90b54-default-rtdb.firebaseio.com',
    storageBucket: 'newtest-90b54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU0OK-Th8uuupUZWWsP66jILYZDx92ntQ',
    appId: '1:1065906049975:ios:a1f8d6e01f78a961f44e32',
    messagingSenderId: '1065906049975',
    projectId: 'newtest-90b54',
    databaseURL: 'https://newtest-90b54-default-rtdb.firebaseio.com',
    storageBucket: 'newtest-90b54.appspot.com',
    iosClientId: '1065906049975-99k5qej6ulrqtvk5qnken4ku3a0uupag.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU0OK-Th8uuupUZWWsP66jILYZDx92ntQ',
    appId: '1:1065906049975:ios:086f7b14341208f7f44e32',
    messagingSenderId: '1065906049975',
    projectId: 'newtest-90b54',
    databaseURL: 'https://newtest-90b54-default-rtdb.firebaseio.com',
    storageBucket: 'newtest-90b54.appspot.com',
    iosClientId: '1065906049975-sioucbqhamu26h9995kh6pe8l7ig04ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingapp.RunnerTests',
  );
}
